### ISSUE TITLE
InfluxDB 0.13 will be supported?

### ISSUE THREAD

**Issue by mrh666** [vimeo/graphite-influxdb#54]
Hi there,

Is there is any chance that InfluxDB 0.13 will be supported?

I've tested graphite-influxdb with latest brutasse/graphite-api as well as with Dieterbe/graphite-api.
I've got a wrong response (for /metrics/find?query=*) from graphite-api: ```[{"text": "results", "id": "results", "allowChildren": 0, "expandable": 0, "leaf": 1}```

But I have a bunch of properly tagged metrics in InfluxDB...

graphite-api.yaml fragment:
```
search_index: /srv/graphite/index
finders:
  - graphite_influxdb.InfluxdbFinder
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
influxdb:
   host: influxdb.dev.mydomain.com
   port: 8086
   user: graphite
   pass: graphite
   db:   metrics
   schema:
     - ['', 60]
     - ['high-res-metrics', 10]
...
```

Any ideas hot to make it work?
